---
include:
  - board: raytac_mdbt50q_rx
    shield: corne_dongle
    artifact-name: raytac_mdbt50q_rx_corne_dongle

  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nice_nano_v2_corne_left_peripheral
    snippet: zmk-usb-logging

  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nice_nano_v2_corne_right_peripheral
    snippet: zmk-usb-logging

  - board: raytac_mdbt50q_rx
    shield: settings_reset
    artifact-name: raytac_mdbt50q_rx_settings_reset

  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nice_nano_v2_settings_reset
